version: '2.3'

services:
  task:
    container_name: nav_journal
    image: image_nav_journal
    build: service
    restart: always
    ports:
      - 33013:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    volumes:
      - ./service/nsjail/logs/:/var/log/nsjail/
