version: '2.3'

services:
  task:
    container_name: plane_market
    image: image_plane_market
    build: service
    restart: always
    ports:
      - 33087:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    volumes:
      - ./service/nsjail/logs/:/var/log/nsjail/
