version: '2.3'

services:
  task:
    container_name: save_plane
    image: image_save_plane
    build: service
    restart: always
    ports:
      - 33027:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    volumes:
      - ./service/nsjail/logs/:/var/log/nsjail/
