version: '2.3'

services:
  task:
    container_name: 1001and1nigth
    image: image_1001and1nigth
    build: service
    restart: always

    mem_limit: 512M
    memswap_limit: 512M
    pids_limit: 1024

    ulimits:
      nofile:
        soft: 1024
        hard: 1024

    ports:
      - 44324:31337